import { BANK_SKILLS } from './bank.data';
import { Skill, Operation } from './types';

export { createSampler } from './sampler';
export type { Sampler } from './sampler';

// The curriculum ladder is derived from the CSV question bank (bank.data.ts,
// generated by `pnpm build:bank`). Levels come from the distinct (lab, SKILL)
// pairs; the served questions themselves live in the bank runtime (bank.ts).
export const ALL_SKILLS: Skill[] = BANK_SKILLS;

const byId = new Map(ALL_SKILLS.map((l) => [l.id, l]));

export function getSkill(id: string): Skill {
  const skill = byId.get(id);
  if (!skill) throw new Error(`Unknown skill: ${id}`);
  return skill;
}

export function skillsForLab(lab: Operation): Skill[] {
  return ALL_SKILLS.filter((l) => l.lab === lab).sort(
    (a, b) => a.level - b.level || a.ordinal - b.ordinal
  );
}

export function skillsForLevel(lab: Operation, level: number): Skill[] {
  return skillsForLab(lab).filter((l) => l.level === level);
}

export function levelsForLab(lab: Operation): number[] {
  return [...new Set(skillsForLab(lab).map((l) => l.level))].sort((a, b) => a - b);
}
