import { BANK_LEVELS } from './bank.data';
import { Level, Operation } from './types';

export { createSampler } from './sampler';
export type { Sampler } from './sampler';

// The curriculum ladder is derived from the CSV question bank (bank.data.ts,
// generated by `pnpm build:bank`). Levels come from the distinct (lab, SKILL)
// pairs; the served questions themselves live in the bank runtime (bank.ts).
export const ALL_LEVELS: Level[] = BANK_LEVELS;

const byId = new Map(ALL_LEVELS.map((l) => [l.id, l]));

export function getLevel(id: string): Level {
  const level = byId.get(id);
  if (!level) throw new Error(`Unknown level: ${id}`);
  return level;
}

export function levelsForLab(lab: Operation): Level[] {
  return ALL_LEVELS.filter((l) => l.lab === lab).sort(
    (a, b) => a.tingkat - b.tingkat || a.urutan - b.urutan
  );
}

export function levelsForTingkat(lab: Operation, tingkat: number): Level[] {
  return levelsForLab(lab).filter((l) => l.tingkat === tingkat);
}

export function tingkatsForLab(lab: Operation): number[] {
  return [...new Set(levelsForLab(lab).map((l) => l.tingkat))].sort((a, b) => a - b);
}
