import { Level } from '../types';
import { pick, randInt, scale } from '../rng';

// Lab Kali — multiplication ladder (see specs §7).
export const mulLevels: Level[] = [
  {
    id: 'mul.concept',
    lab: 'mul',
    tingkat: 1,
    urutan: 1,
    labelId: 'Perkalian = penjumlahan berulang',
    tipe: 'konsep',
    isCore: false,
    prereqs: [],
    explainId: 'mul.concept',
    generate: (diff) => {
      const a = randInt(2, scale(diff, 3, 5));
      const b = randInt(2, scale(diff, 3, 5));
      return [a, b];
    },
  },
  {
    id: 'mul.table.easy',
    lab: 'mul',
    tingkat: 1,
    urutan: 2,
    labelId: 'Tabel 2, 5, 10',
    tipe: 'fakta',
    isCore: false,
    prereqs: ['mul.concept'],
    explainId: 'mul.table',
    generate: (diff) => [randInt(2, scale(diff, 5, 10)), pick([2, 5, 10])],
  },
  {
    id: 'mul.table.mid',
    lab: 'mul',
    tingkat: 1,
    urutan: 3,
    labelId: 'Tabel 3, 4',
    tipe: 'fakta',
    isCore: false,
    prereqs: ['mul.table.easy'],
    explainId: 'mul.table',
    generate: (diff) => [randInt(2, scale(diff, 5, 10)), pick([3, 4])],
  },
  {
    id: 'mul.table.hard',
    lab: 'mul',
    tingkat: 1,
    urutan: 4,
    labelId: 'Tabel 6, 7, 8, 9',
    tipe: 'fakta',
    isCore: true,
    prereqs: ['mul.table.mid'],
    explainId: 'mul.table',
    generate: (diff) => [randInt(2, scale(diff, 5, 10)), pick([6, 7, 8, 9])],
  },
  {
    id: 'mul.2d.1d',
    lab: 'mul',
    tingkat: 2,
    urutan: 1,
    labelId: '2–3 angka × 1 angka',
    tipe: 'algoritma',
    isCore: false,
    prereqs: ['mul.table.hard'],
    explainId: 'mul.column.1d',
    generate: (diff) => [randInt(12, scale(diff, 49, 999)), randInt(2, 9)],
  },
  {
    id: 'mul.2d.2d',
    lab: 'mul',
    tingkat: 2,
    urutan: 2,
    labelId: '2 angka × 2 angka',
    tipe: 'algoritma',
    isCore: true,
    prereqs: ['mul.2d.1d'],
    explainId: 'mul.column.2d',
    generate: (diff) => [randInt(11, scale(diff, 39, 99)), randInt(11, scale(diff, 29, 99))],
  },
  {
    id: 'mul.multi',
    lab: 'mul',
    tingkat: 2,
    urutan: 3,
    labelId: 'Multi-digit',
    tipe: 'algoritma',
    isCore: false,
    prereqs: ['mul.2d.2d'],
    explainId: 'mul.column.2d',
    generate: (diff) => [randInt(101, scale(diff, 399, 999)), randInt(11, scale(diff, 29, 99))],
  },
];
